maproulette/maproulette-java-client

- .github/workflows/build.yml
- README.md
> Adding automatic release when pushing to master

- .github/workflows/release.yml
> Updating release action

- README.md
- src/main/java/org/maproulette/client/model/Challenge.java
- src/main/java/org/maproulette/client/model/Project.java
- src/main/java/org/maproulette/client/model/Task.java
- src/main/java/org/maproulette/client/utilities/Utilities.java
- src/test/java/org/maproulette/client/serializer/ChallengeSerializationTest.java
- src/test/java/org/maproulette/client/serializer/ProjectSerializationTest.java
- src/test/java/org/maproulette/client/serializer/TaskSerializerTest.java
Also updated the unit tests
Unit tests.
> Added some helper deserialization functions.

- build.gradle
> Including the gradle deployment gradle script

- gradle/uploadAndRelease.sh
> updating nexus profile id

- gradle/wrapper/gradle-wrapper.properties
> upgrading to gradle 5.6

- .travis.yml
> Fixing permissions so the deploy script will run

- gradle.properties
> Updating version after release

- README.md
> Updating release version badge

- src/main/java/org/maproulette/client/api/TaskAPI.java
- src/main/java/org/maproulette/client/model/Task.java
- src/test/java/org/maproulette/client/model/TaskTest.java
Currently we cannot create new tasks in MapRoulette with tags. I've updated tasks so now we can!
Added an assertEquals test for the tag getter.
Tested these changes using a CLI tool to upload new tasks
------
> Adding Tags to Tasks

- src/main/java/org/maproulette/client/model/Challenge.java
- src/test/java/org/maproulette/client/model/ChallengeTest.java
This is just adding a new field `changesetUrl` that is required by MapRoulette
Created unit tests to verify the new fields
N/A
------
> Fixing issues introduced from a breaking API change in the MapRoulette code.

- gradle.properties
> Updating version

- src/main/java/org/maproulette/client/model/Challenge.java
- src/test/java/org/maproulette/client/model/ChallengeTest.java
Added the fields preferredTags, preferredReviewTags, and tags to Challenge
added unittest
N/A
------
> added fields in Challenge model 

- gradle.properties
> Update release version

- .github/workflows/pull-request.yml
- src/integrationTest/java/org/maproulette/client/batch/BatchUploaderIntegrationTest.java
- src/main/java/org/maproulette/client/model/RuleList.java
- src/main/java/org/maproulette/client/utilities/ObjectMapperSingleton.java
- src/main/java/org/maproulette/client/utilities/Utilities.java
- src/test/java/org/maproulette/client/serializer/ChallengeSerializationTest.java
- src/test/java/org/maproulette/client/serializer/RuleListSerializationDeserializationTest.java
There was a previous commit that was added to the repository and caused issues in the release pipeline. To resolve this, I'm adding a github action to run the necessary syntax checks for all pull requests to the project, and also resolving the existing format issues.
N/A
Pull requests that do not have properly formatted files will fail. I did test this failure with this PR.
------
> Create gh action for pull requests and resolve existing formatting issues

- .github/workflows/pull-request.yml
- src/integrationTest/java/org/maproulette/client/batch/BatchUploaderIntegrationTest.java
- src/main/java/org/maproulette/client/model/RuleList.java
- src/main/java/org/maproulette/client/utilities/ObjectMapperSingleton.java
- src/main/java/org/maproulette/client/utilities/Utilities.java
- src/test/java/org/maproulette/client/serializer/ChallengeSerializationTest.java
- src/test/java/org/maproulette/client/serializer/RuleListSerializationDeserializationTest.java
> Merging to main

- .github/workflows/pull-request.yml
Run CI integration tests for PRs and branches
N/A
GH action passes
> Run CI integration tests for PRs and branches

- src/integrationTest/java/org/maproulette/client/batch/BatchUploaderIntegrationTest.java
- src/main/java/org/maproulette/client/batch/ChallengeBatch.java
- src/main/java/org/maproulette/client/connection/MapRouletteConfiguration.java
Lower batch limit of tasks allowed in a challenge task batch upload.
Re-ran batchTest
batchTest succeeds
------
> lower batch limit

- build.gradle
Eliminate some CVEs by updating Apache Httpclient
- Apache httpclient 4.5.1 to 4.5.14
> Update apache httpclient

- .github/workflows/publish-release.yml
- .github/workflows/publish-snapshot.yml
- .github/workflows/pull-request.yml
GH Action maintenance for the project: update some versions, use better cache mechanism, don't trigger on PR (it's triggered every push).
Not applicable.
GH Action build is successful.
> Update GH Actions to use newer versions and cache mechanisms

- src/integrationTest/java/org/maproulette/client/api/ChallengeAPIIntegrationTest.java
- src/main/java/org/maproulette/client/model/Challenge.java
- src/test/java/org/maproulette/client/serializer/ChallengeSerializationTest.java
- src/test/resources/challenges/testChallenge2.json
- src/test/resources/challenges/testChallenge4.json
Added a new property `taskWidgetLayout` of type `JsonNode` to the `Challenge` model, which is an optional JSON object to store additional layout information for tasks. Updated `ChallengeAPIIntegrationTest`, `ChallengeSerializationTest`, and test challenge JSON files to include and validate the new `taskWidgetLayout` property.
Several unit tests and integration tests were updated to validate the challenge.taskWidgetLayout field.
The unit test and integration tests (which does use a backend and db!) are passing.
> Add taskWidgetLayout property to Challenge model and update tests

- gradle.properties
Update version to 0.4.6-SNAPSHOT to prepare for a published release.
> Update version to 0.4.6-SNAPSHOT
